/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.ComboboxBLL;
import BLL.HangHoaSPBLL;
import BLL.LoaiSanPhamBLL;
import DAL.ConnectionDB;
import DAL.HangHoaSPDAL;
import DTO.DinhNghiaComboBox;
import DTO.HangHoaSPDTO;
import DTO.LoaiSanPhamDTO;
import FormNho.*;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author Ridotoji Pham
 */
public class FrmHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form FrmHangHoa
     */
    public FrmHangHoa() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        JpnHanghoa = new javax.swing.JPopupMenu();
        MnHanhHoa = new javax.swing.JMenuItem();
        Jpntonkho = new javax.swing.JPopupMenu();
        Jmntonkho = new javax.swing.JMenuItem();
        HangHoa = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnthemdonhang = new javax.swing.JButton();
        btnsuadonhang = new javax.swing.JButton();
        btnxoadonhang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldonhang = new javax.swing.JTable();
        btnxuat = new javax.swing.JButton();
        lbltimkiem = new javax.swing.JLabel();
        cbbLoaiHanghoa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtmasanpham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbMaLoai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txttensanpham = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsoseri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtngaynhap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGianhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGIaBan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdonvitinh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txthanbaohanh = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtmota = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbbNhomHang = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltonkhoHangHoa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        MnHanhHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        MnHanhHoa.setText("ReSet");
        MnHanhHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHanhHoaActionPerformed(evt);
            }
        });
        JpnHanghoa.add(MnHanhHoa);

        Jmntonkho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        Jmntonkho.setText("Reset");
        Jmntonkho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmntonkhoActionPerformed(evt);
            }
        });
        Jpntonkho.add(Jmntonkho);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bảng Hàng Hóa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnthemdonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Them.png"))); // NOI18N
        btnthemdonhang.setText("Thêm");
        btnthemdonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthemdonhangMouseClicked(evt);
            }
        });

        btnsuadonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        btnsuadonhang.setText("Sửa");
        btnsuadonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsuadonhangMouseClicked(evt);
            }
        });

        btnxoadonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnxoadonhang.setText("Xóa");
        btnxoadonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxoadonhangMouseClicked(evt);
            }
        });
        btnxoadonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadonhangActionPerformed(evt);
            }
        });

        txttimkiem.setToolTipText("");
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        tbldonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Đơn hàng", "Đơn vị", "Số lượng", "Giá mua", "Giá bán", "Bảo hành"
            }
        ));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JpnHanghoa, org.jdesktop.beansbinding.ObjectProperty.create(), tbldonhang, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        tbldonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldonhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldonhang);

        btnxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        btnxuat.setText("Xuất");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });

        lbltimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        lbltimkiem.setText("Tìm kiếm:");
        lbltimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltimkiemMouseClicked(evt);
            }
        });

        cbbLoaiHanghoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPhone", "Item 2", "Item 3", "Item 4" }));
        cbbLoaiHanghoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiHanghoaItemStateChanged(evt);
            }
        });
        cbbLoaiHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbLoaiHanghoaMouseClicked(evt);
            }
        });

        jLabel4.setText("Mã sản Phẩm:");

        txtmasanpham.setEditable(false);

        jLabel5.setText("Mã Loại Sản Phẩm:");

        cbbMaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tên Sản Phẩm:");

        jLabel7.setText("Số seri:");

        jLabel8.setText("Ngày Nhập:");

        jLabel9.setText("Giá Nhập:");

        jLabel10.setText("Số Lượng:");

        jLabel11.setText("Giá Bán:");

        jLabel12.setText("Đơn vị tính:");

        jLabel13.setText("Hạn Bảo hành:");

        jLabel14.setText("Mô Tả:");

        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        btnclear.setText("Làm Mới");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbLoaiHanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbltimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxuat)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnthemdonhang)
                                        .addGap(16, 16, 16)
                                        .addComponent(btnxoadonhang)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnsuadonhang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnclear)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtngaynhap, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                                        .addComponent(txttensanpham))
                                                    .addComponent(txtdonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbMaLoai, 0, 358, Short.MAX_VALUE)
                                    .addComponent(txtsoseri)
                                    .addComponent(txtGianhap)
                                    .addComponent(txtGIaBan)
                                    .addComponent(txthanbaohanh)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addComponent(txtmota)))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthemdonhang)
                        .addComponent(btnsuadonhang)
                        .addComponent(btnxoadonhang)
                        .addComponent(lbltimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnxuat)
                        .addComponent(btnclear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoaiHanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbbMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtsoseri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtGIaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtdonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txthanbaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtmota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HangHoa.addTab("Hàng Hóa", jPanel1);

        cbbNhomHang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhóm Hàng", "--------", "Item 2", "Item 3", "Item 4" }));
        cbbNhomHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhomHangItemStateChanged(evt);
            }
        });
        cbbNhomHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbNhomHangMouseClicked(evt);
            }
        });

        tbltonkhoHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên hàng", "Đơn vị", "Số lượng", "Mua vào", "Trị giá"
            }
        ));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Jpntonkho, org.jdesktop.beansbinding.ObjectProperty.create(), tbltonkhoHangHoa, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        tbltonkhoHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltonkhoHangHoaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltonkhoHangHoa);

        jLabel3.setText("Trị giá :");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbbNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        HangHoa.addTab("Tồn kho", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HangHoa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HangHoa)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemdonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemdonhangMouseClicked
        // TODO add your handling code here:
          int IDSanPham;
        int MaLoaiSanPham = Integer.parseInt(ComboboxBLL.getSelectedItemID(cbbMaLoai));
        String TenSanPham = txttensanpham.getText();
        String Imei = txtsoseri.getText();
        String NgayNhap = txtngaynhap.getText();
        String GiaNhap = txtGianhap.getText();
        int soluong = Integer.parseInt(txtsoluong.getText());
        String GiaBan = txtGIaBan.getText();
        String DonViTinh = txtdonvitinh.getText();
        String HanBaoHanh = txthanbaohanh.getText();
        String MoTa = txtmota.getText();
        HangHoaSPDTO HH = new HangHoaSPDTO(0, MaLoaiSanPham, TenSanPham, Imei, NgayNhap, GiaNhap, soluong, GiaBan, DonViTinh, HanBaoHanh, MoTa);
        HangHoaSPBLL.ThemDonhang(HH);
         ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
        HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
    }//GEN-LAST:event_btnthemdonhangMouseClicked

    private void btnsuadonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuadonhangMouseClicked
        // TODO add your handling code here:
        int IDSanPham = Integer.parseInt(txtmasanpham.getText());
        int MaLoaiSanPham = Integer.parseInt(ComboboxBLL.getSelectedItemID(cbbMaLoai));
        String TenSanPham = txttensanpham.getText();
        String Imei = txtsoseri.getText();
        String NgayNhap = txtngaynhap.getText();
        String GiaNhap = txtGianhap.getText();
        int soluong = Integer.parseInt(txtsoluong.getText());
        String GiaBan = txtGIaBan.getText();
        String DonViTinh = txtdonvitinh.getText();
        String HanBaoHanh = txthanbaohanh.getText();
        String MoTa = txtmota.getText();
        HangHoaSPDTO HH = new HangHoaSPDTO(IDSanPham, MaLoaiSanPham, TenSanPham, Imei, NgayNhap, GiaNhap, soluong, GiaBan, DonViTinh, HanBaoHanh, MoTa);
        HangHoaSPBLL.SuaDonhang(HH);
          ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
        HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
    }//GEN-LAST:event_btnsuadonhangMouseClicked

    private void btnxoadonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoadonhangMouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_btnxoadonhangMouseClicked

    private void lbltimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltimkiemMouseClicked
        // TODO add your handling code here:
          String tuKhoa = txttimkiem.getText();
       //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTuKhoa(tuKhoa);
       //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
      HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
    }//GEN-LAST:event_lbltimkiemMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
         HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs,tbldonhang);
         
        ResultSet rs1 = HangHoaSPBLL.LayTatCaLSP();
       ComboboxBLL.LoadDuLieuCombobox(rs1, cbbNhomHang, "TenLoaiSanPham", "MaLoaiSanPham");
        
       ResultSet rs2 = HangHoaSPBLL.LayTatCaLSP();
        ComboboxBLL.LoadDuLieuCombobox(rs2, cbbLoaiHanghoa, "TenLoaiSanPham", "MaLoaiSanPham");
         
          ResultSet rs3 = HangHoaSPBLL.Laybangtonkho();
        HangHoaSPBLL.DoDuLieuVaoJTableBangtonkho(rs3,tbltonkhoHangHoa);
        
        HangHoaSPBLL.DoDuLieuVaoJTablesanpham(HangHoaSPBLL.LayTatCaSanPham(), tbldonhang);
         ResultSet rs4 = HangHoaSPBLL.LayTatCaLSP();
        ComboboxBLL.LoadDuLieuCombobox(rs4, cbbMaLoai, "TenLoaiSanPham", "MaLoaiSanPham");
       jTextField3.setText(HangHoaSPBLL.TinhTien(tbltonkhoHangHoa, 4) + " VND");
    }//GEN-LAST:event_formWindowOpened

    private void cbbNhomHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbNhomHangMouseClicked
      
    }//GEN-LAST:event_cbbNhomHangMouseClicked

    private void cbbNhomHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhomHangItemStateChanged
    if(evt.getStateChange() == 1){
            String maLoaiSPDuocChon = ComboboxBLL.getSelectedItemID(cbbNhomHang);
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTenSanPham(maLoaiSPDuocChon,maLoaiSPDuocChon);
            HangHoaSPBLL.DoDuLieuVaoJTableBangtonkho(rs, tbltonkhoHangHoa);
        }
    }//GEN-LAST:event_cbbNhomHangItemStateChanged
 public void setSelectedCombobox(String cbbselected) {
         for(int i = 0; i < cbbMaLoai.getItemCount(); i++){
            Object obj = cbbMaLoai.getItemAt(i);
            if(obj != null){
                DTO.DinhNghiaComboBox m = (DTO.DinhNghiaComboBox) obj;
                if(cbbselected.equals(m.DisplayMmber)){
                    cbbMaLoai.setSelectedItem(m);
                }
            }        
        }
    }
    private void tbldonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldonhangMouseClicked
        // TODO add your handling code here:
            int index = tbldonhang.getSelectedRow();
        txtmasanpham.setText(tbldonhang.getValueAt(index, 0).toString());
         String tenLoai = tbldonhang.getValueAt(index, 1).toString();
        setSelectedCombobox(tenLoai);
           txttensanpham.setText(tbldonhang.getValueAt(index, 2).toString());
          txtsoseri.setText(tbldonhang.getValueAt(index, 3).toString());
          txtngaynhap.setText(tbldonhang.getValueAt(index, 4).toString());
          txtGianhap.setText(tbldonhang.getValueAt(index, 5).toString());
          txtsoluong.setText(tbldonhang.getValueAt(index, 6).toString());
          txtGIaBan.setText(tbldonhang.getValueAt(index, 7).toString());
          txtdonvitinh.setText(tbldonhang.getValueAt(index, 8).toString());
          txthanbaohanh.setText(tbldonhang.getValueAt(index, 9).toString());
           txtmota.setText(tbldonhang.getValueAt(index, 10).toString());
    }//GEN-LAST:event_tbldonhangMouseClicked

    private void cbbLoaiHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLoaiHanghoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiHanghoaMouseClicked
 
    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
         try {
           Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-A7029VT\\SQLEXPRESS"
            + ";databaseName=QuanLyBanHang;user=sa;password=123;");
           JasperDesign jasperDesign = JRXmlLoader.load("D:\\PhanMemDuAn01\\DuAn1-PhanMemQLBanHang\\DuAn1-PhanMemQLBanHang\\PhanMemQLBanHang\\src\\Report\\SanPham.jrxml");
            String sql = "select * from SanPham";
            JRDesignQuery newQuyery = new JRDesignQuery();
            newQuyery.setText(sql);
            jasperDesign.setQuery(newQuyery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, new HashMap(),conn);
            JasperViewer.viewReport(jasperPrint);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this ,e.getMessage());
        }
    }//GEN-LAST:event_btnxuatActionPerformed

    private void cbbLoaiHanghoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiHanghoaItemStateChanged
if(evt.getStateChange() == 1){
            String maLoaiSPDuocChon = ComboboxBLL.getSelectedItemID(cbbLoaiHanghoa);
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTenSanPham(maLoaiSPDuocChon,maLoaiSPDuocChon);
            HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
        }
    }//GEN-LAST:event_cbbLoaiHanghoaItemStateChanged

    private void btnxoadonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadonhangActionPerformed
        // TODO add your handling code here:
                int[] cacViTriDuocChon = tbldonhang.getSelectedRows();
           for(int i = 0; i < cacViTriDuocChon.length; i++){
    String MaLoaiCanXoa = tbldonhang.getValueAt(cacViTriDuocChon[i], 0).toString() ;
     //Gọi hàm xóa ở tầng xử lý
            HangHoaSPBLL.XoaDonHang(MaLoaiCanXoa);
         }
           ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
        //Đọc lại dữ liệu và đổ lại dữ liệu
       HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);  
    }//GEN-LAST:event_btnxoadonhangActionPerformed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
             String tuKhoa = txttimkiem.getText();
       //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTuKhoa(tuKhoa);
       //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
      HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void tbltonkhoHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltonkhoHangHoaMouseClicked
        // TODO add your handling code here:
       jTextField3.setText(HangHoaSPBLL.TinhTien(tbltonkhoHangHoa, 4) + " VND");
    }//GEN-LAST:event_tbltonkhoHangHoaMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtmasanpham.setText("");txtGIaBan.setText("");txtGianhap.setText("");txtdonvitinh.setText("");txthanbaohanh.setText("");
        txtmota.setText("");txtngaynhap.setText("");txtsoluong.setText("");txtsoseri.setText("");txttensanpham.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
         jTextField3.setText(HangHoaSPBLL.TinhTien(tbltonkhoHangHoa, 4) + " VND");
    }//GEN-LAST:event_jTextField3KeyReleased

    private void MnHanhHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHanhHoaActionPerformed
        // TODO add your handling code here:
        ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
          HangHoaSPBLL.DoDuLieuVaoJTablesanpham(rs, tbldonhang);
    }//GEN-LAST:event_MnHanhHoaActionPerformed

    private void JmntonkhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmntonkhoActionPerformed
        // TODO add your handling code here:
       ResultSet rs = HangHoaSPBLL.LayTatCaSanPham();
            HangHoaSPBLL.DoDuLieuVaoJTableBangtonkho(rs, tbltonkhoHangHoa);
    }//GEN-LAST:event_JmntonkhoActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane HangHoa;
    private javax.swing.JMenuItem Jmntonkho;
    private javax.swing.JPopupMenu JpnHanghoa;
    private javax.swing.JPopupMenu Jpntonkho;
    private javax.swing.JMenuItem MnHanhHoa;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsuadonhang;
    private javax.swing.JButton btnthemdonhang;
    private javax.swing.JButton btnxoadonhang;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbbLoaiHanghoa;
    private javax.swing.JComboBox<String> cbbMaLoai;
    private javax.swing.JComboBox cbbNhomHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbltimkiem;
    private javax.swing.JTable tbldonhang;
    private javax.swing.JTable tbltonkhoHangHoa;
    private javax.swing.JTextField txtGIaBan;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtdonvitinh;
    private javax.swing.JTextField txthanbaohanh;
    private javax.swing.JTextField txtmasanpham;
    private javax.swing.JTextField txtmota;
    private javax.swing.JTextField txtngaynhap;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtsoseri;
    private javax.swing.JTextField txttensanpham;
    private javax.swing.JTextField txttimkiem;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}

