/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.ChiTietHDNhapBLL;
import BLL.ComboboxBLL;
import BLL.HoaDonNhapBLL;
import BLL.NhaCungCapBLL;
import BLL.NhapHangSPBLL;
import DAL.ChiTietHDNhapDAL;
import DAL.HoaDonNhapDAL;
import DAL.NhaCungCapDAL;
import DAL.NhapHangSPDAL;
import DTO.*;
import FormNho.FrmCTHDN;
import FormNho.FrmSuaCTHDN;
import FormNho.FrmSuaHDN;
import FormNho.FrmSuaNCC;
import FormNho.FrmSuaTenSP;
import FormNho.FrmThemHDN;
import FormNho.FrmThemNCC;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ridotoji Pham
 */
public class FrmNhapHang extends javax.swing.JFrame {

    /**
     * Creates new form FrmNhapHang
     */
    public FrmNhapHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PopupNhapHang = new javax.swing.JPopupMenu();
        Sửa = new javax.swing.JMenuItem();
        Xóa = new javax.swing.JMenuItem();
        PopupCTHDN = new javax.swing.JPopupMenu();
        SửaCTHDN = new javax.swing.JMenuItem();
        XoáCTHDN = new javax.swing.JMenuItem();
        PopupHDN = new javax.swing.JPopupMenu();
        ThêmHD = new javax.swing.JMenuItem();
        SửaHD = new javax.swing.JMenuItem();
        XóaHD = new javax.swing.JMenuItem();
        NhapHang = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIMEI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMoTaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblChiTietHDNhap = new javax.swing.JTable();
        txtDonViTinh = new javax.swing.JTextField();
        txtHanBH = new javax.swing.JTextField();
        lblMaChiTietHDNhap = new javax.swing.JLabel();
        txtMaChiTietHDNhap = new javax.swing.JTextField();
        spnSoLuong = new javax.swing.JSpinner();
        bntOK = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        jdNgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtMaHDNhap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHDNhap = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSP = new javax.swing.JTable();
        cbbLoaiSP = new javax.swing.JComboBox();
        txtTimKiemSP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThemNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();
        txtTimKiemNCC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        Sửa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        Sửa.setText("Sửa");
        Sửa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SửaActionPerformed(evt);
            }
        });
        PopupNhapHang.add(Sửa);

        Xóa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        Xóa.setText("Xóa");
        Xóa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XóaActionPerformed(evt);
            }
        });
        PopupNhapHang.add(Xóa);

        SửaCTHDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        SửaCTHDN.setText("Sửa");
        SửaCTHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SửaCTHDNActionPerformed(evt);
            }
        });
        PopupCTHDN.add(SửaCTHDN);

        XoáCTHDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        XoáCTHDN.setText("Xoá");
        XoáCTHDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoáCTHDNActionPerformed(evt);
            }
        });
        PopupCTHDN.add(XoáCTHDN);

        ThêmHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Them.png"))); // NOI18N
        ThêmHD.setText("Thêm");
        ThêmHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThêmHDActionPerformed(evt);
            }
        });
        PopupHDN.add(ThêmHD);

        SửaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        SửaHD.setText("Sửa");
        SửaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SửaHDActionPerformed(evt);
            }
        });
        PopupHDN.add(SửaHD);

        XóaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        XóaHD.setText("Xóa");
        XóaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XóaHDActionPerformed(evt);
            }
        });
        PopupHDN.add(XóaHD);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 483));

        jLabel3.setText("ID Sản phẩm:");

        txtIDSP.setEditable(false);

        jLabel4.setText("Tên sản phẩm:");

        jLabel6.setText("Số seri:");

        jLabel7.setText("Đơn Giá:");

        jLabel8.setText("Số lượng:");

        jLabel15.setText("Ngày nhập:");

        jLabel16.setText("Giá bán:");

        jLabel22.setText("Đơn vị tính:");

        jLabel5.setText("Hạn bảo hành:");

        jLabel23.setText("Mô tả:");

        tblChiTietHDNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chi Tiết HD Nhập", "Mã HD Nhập", "ID Sản Phẩm", "Số Lượng", "Đơn Vị Tính", "Đơn Giá", "Thành Tiền", "Mô Tả"
            }
        ));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, PopupCTHDN, org.jdesktop.beansbinding.ObjectProperty.create(), tblChiTietHDNhap, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jScrollPane7.setViewportView(tblChiTietHDNhap);
        if (tblChiTietHDNhap.getColumnModel().getColumnCount() > 0) {
            tblChiTietHDNhap.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblChiTietHDNhap.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblChiTietHDNhap.getColumnModel().getColumn(2).setPreferredWidth(25);
            tblChiTietHDNhap.getColumnModel().getColumn(3).setPreferredWidth(30);
            tblChiTietHDNhap.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblChiTietHDNhap.getColumnModel().getColumn(5).setPreferredWidth(30);
            tblChiTietHDNhap.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        lblMaChiTietHDNhap.setText("Mã chi tiết HD nhập:");

        txtMaChiTietHDNhap.setEditable(false);

        bntOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        bntOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOKActionPerformed(evt);
            }
        });

        btnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã HD nhập:");

        txtMaHDNhap.setEditable(false);

        jLabel14.setText("Thành tiền:");

        txtThanhTien.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("Bảng Hóa Đơn Nhập");

        tblHDNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HDN", "Số HDN", "Ngày Tạo", "Mã NV", "Mã NCC", "Tình Trạng", "Tổng Tiền", "Mô Tả"
            }
        ));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, PopupHDN, org.jdesktop.beansbinding.ObjectProperty.create(), tblHDNhap, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        tblHDNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHDNhap);
        if (tblHDNhap.getColumnModel().getColumnCount() > 0) {
            tblHDNhap.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblHDNhap.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblHDNhap.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblHDNhap.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblHDNhap.getColumnModel().getColumn(4).setPreferredWidth(55);
        }

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Bảng Chi Tiết Hóa Đơn Nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(bntOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHanBH, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtGiaBan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMoTaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(633, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                            .addComponent(txtIMEI))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnSoLuong)
                                            .addComponent(jdNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMaChiTietHDNhap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaChiTietHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaHDNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(227, 227, 227)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblMaChiTietHDNhap)
                            .addComponent(txtMaChiTietHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtMaHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel15))
                            .addComponent(jdNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel23)
                            .addComponent(txtMoTaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHanBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(jLabel2))
        );

        tblDanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Sản Phẩm", "Tên Sản Phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, PopupNhapHang, org.jdesktop.beansbinding.ObjectProperty.create(), tblDanhSachSP, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        tblDanhSachSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachSP);

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "HTC", "Oppo", "Iphone", "SamSung", "LG" }));
        cbbLoaiSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiSPItemStateChanged(evt);
            }
        });

        txtTimKiemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSPActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        jLabel1.setText("Nhóm :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, Short.MAX_VALUE))
        );

        NhapHang.addTab("Nhập Hàng", jPanel2);

        btnThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Them.png"))); // NOI18N
        btnThemNCC.setText("Thêm");
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnSuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        btnSuaNCC.setText("Sửa");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnXoaNCC.setText("Xóa");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Địa Chỉ", "Số Điện Thoại", "Mô Tả"
            }
        ));
        jScrollPane4.setViewportView(tblNCC);
        if (tblNCC.getColumnModel().getColumnCount() > 0) {
            tblNCC.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        txtTimKiemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemNCCActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel11.setText("Tìm kiếm :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThemNCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaNCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaNCC)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemNCC)
                        .addComponent(btnSuaNCC)
                        .addComponent(btnXoaNCC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        NhapHang.addTab("Nhà Cung Cấp", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhapHang)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        // TODO add your handling code here:
        FrmSuaNCC frm = new FrmSuaNCC();
        frm.show();
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        // TODO add your handling code here:
        FrmThemNCC frm = new FrmThemNCC();
        frm.show();
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:      
        ResultSet rs1 = NhaCungCapDAL.Select();
        NhaCungCapBLL.DoDuLieu(rs1, tblNCC);

        ResultSet rs2 = NhapHangSPDAL.LayMaVaTenSanPham();
        NhapHangSPBLL.LayMaVaTenSP(rs2, tblDanhSachSP);

        ResultSet rs3 = ChiTietHDNhapDAL.LayTatCaHDNhap();
        ChiTietHDNhapBLL.DoDuLieu(rs3, tblChiTietHDNhap);

        ResultSet rs4 = HoaDonNhapDAL.LayTatCaHD();
        HoaDonNhapBLL.DanhSachMaHD(rs4, tblHDNhap);

        ResultSet rs = NhapHangSPDAL.LayTenLoaiSanPham();
        ComboboxBLL.LoadDuLieuCombobox(rs, cbbLoaiSP, "TenLoaiSanPham", "MaLoaiSanPham");
    }//GEN-LAST:event_formWindowOpened

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        // TODO add your handling code here:
        int[] cacVitriduocchon = tblNCC.getSelectedRows();
        // Hàm xóa các vị trí cần xóa
        for (int i = 0; i < cacVitriduocchon.length; i++) {
            String MaLoaicanxoa = tblNCC.getValueAt(cacVitriduocchon[i], 0).toString();
            NhaCungCapBLL.Xoa(MaLoaicanxoa);
        }
        ResultSet rs = NhaCungCapBLL.LayTatCaNCC();
        NhaCungCapBLL.DoDuLieu(rs, tblNCC);
    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void txtTimKiemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemNCCActionPerformed
        // TODO add your handling code here:
        String tuKhoa = txtTimKiemNCC.getText();
        //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = NhaCungCapBLL.LayNCCTheoTuKhoa(tuKhoa);
        //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
        NhaCungCapBLL.DoDuLieu(rs, tblNCC);
    }//GEN-LAST:event_txtTimKiemNCCActionPerformed

    private void SửaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SửaActionPerformed
        // TODO add your handling code here:
        FrmSuaTenSP frm = new FrmSuaTenSP();
        frm.show();
    }//GEN-LAST:event_SửaActionPerformed

    private void XóaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XóaActionPerformed
        // TODO add your handling code here:
        int[] cacVitriduocchon = tblDanhSachSP.getSelectedRows();
        // Hàm xóa các vị trí cần xóa
        for (int i = 0; i < cacVitriduocchon.length; i++) {
            String MaLoaicanxoa = tblDanhSachSP.getValueAt(cacVitriduocchon[i], 0).toString();
            NhapHangSPBLL.XoaTenSP(MaLoaicanxoa);
        }
        ResultSet rs = NhapHangSPBLL.LayTatCaTenSP();
        NhapHangSPBLL.LayMaVaTenSP(rs, tblDanhSachSP);
    }//GEN-LAST:event_XóaActionPerformed

    private void txtTimKiemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSPActionPerformed
        // TODO add your handling code here:
        String tuKhoa = txtTimKiemSP.getText();
        //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = NhapHangSPBLL.LaySanPhamTheoTuKhoa(tuKhoa);
        //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
        NhapHangSPBLL.LayMaVaTenSP(rs, tblDanhSachSP);
    }//GEN-LAST:event_txtTimKiemSPActionPerformed

    private void tblDanhSachSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSPMouseClicked
        // TODO add your handling code here:
        int vitri = tblDanhSachSP.getSelectedRow();
        int idsp = Integer.parseInt(tblDanhSachSP.getValueAt(vitri, 0).toString());

        ResultSet rs = NhapHangSPDAL.LaySPTheoIDSP(idsp);

        JTable tblTam = new JTable();
        NhapHangSPBLL.DanhSachSanPham(rs, tblTam);

        txtIDSP.setText(tblTam.getValueAt(0, 0).toString());
        txtTenSP.setText(tblTam.getValueAt(0, 1).toString());
        txtIMEI.setText(tblTam.getValueAt(0, 2).toString());
        txtGiaNhap.setText(tblTam.getValueAt(0, 3).toString());
        txtDonViTinh.setText(tblTam.getValueAt(0, 4).toString());
        txtHanBH.setText(tblTam.getValueAt(0, 5).toString());

    }//GEN-LAST:event_tblDanhSachSPMouseClicked

    private void bntOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOKActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String time = sdf.format(date);
        
        try {
            int idsp = Integer.parseInt(txtIDSP.getText());
            int mahd = Integer.parseInt(txtMaHDNhap.getText());
            int soluong = Integer.parseInt(spnSoLuong.getValue().toString());
            double gianhap = Double.parseDouble(txtGiaNhap.getText());
            String donvitinh = txtDonViTinh.getText();

            double thanhtien = gianhap * soluong;
            String mota = txtMoTaSP.getText();

            ChiTietHDNhapDTO ctHDN = new ChiTietHDNhapDTO(0, mahd, idsp, soluong, donvitinh, gianhap, thanhtien, mota);
            ChiTietHDNhapBLL.Them(ctHDN);
            ResultSet rs = ChiTietHDNhapBLL.LayTatCaHoaDonNhap();
            ChiTietHDNhapBLL.DoDuLieu(rs, tblChiTietHDNhap);
        } catch (NumberFormatException e) {
            MainClass.ThongBao("Chọn Sản Phẩm", "ThongBao", 1);
        }
        /*try {
            mahd = Integer.parseInt(txtMaHDNhap.getText());
        } catch (NumberFormatException e) {
            MainClass.ThongBao("Chọn Hóa Đơn", "ThongBao", 1);
        }
        try {
            gianhap = Double.parseDouble(txtGiaNhap.getText());
        } catch (NumberFormatException e) {
            MainClass.ThongBao("Nhập Giá", "ThongBao", 1);
        }
        try {
            soluong = Integer.parseInt(spnSoLuong.getValue().toString());
        } catch (NumberFormatException e) {
            MainClass.ThongBao("Nhập Số Lượng", "ThongBao", 1);
        }*/


    }//GEN-LAST:event_bntOKActionPerformed

    private void tblHDNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDNhapMouseClicked
        // TODO add your handling code here:
        int vitri = tblHDNhap.getSelectedRow();
        int mahdnhap = Integer.parseInt(tblHDNhap.getValueAt(vitri, 0).toString());

        ResultSet rs = HoaDonNhapDAL.LayMaHDNhap(mahdnhap);

        JTable tblTam = new JTable();
        HoaDonNhapBLL.DanhSachMaHD(rs, tblTam);

        txtMaHDNhap.setText(tblTam.getValueAt(0, 0).toString());
    }//GEN-LAST:event_tblHDNhapMouseClicked

    private void cbbLoaiSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiSPItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 1) {
            String maloaisp = ComboboxBLL.getSelectedItemID(cbbLoaiSP);
            ResultSet rs = NhapHangSPBLL.LaySanPhamTheoTen(maloaisp);
            NhapHangSPBLL.LayMaVaTenSP(rs, tblDanhSachSP);
        }
    }//GEN-LAST:event_cbbLoaiSPItemStateChanged

    private void SửaCTHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SửaCTHDNActionPerformed
        // TODO add your handling code here:
        FrmSuaCTHDN frm = new FrmSuaCTHDN();
        frm.show();
    }//GEN-LAST:event_SửaCTHDNActionPerformed

    private void XoáCTHDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoáCTHDNActionPerformed
        // TODO add your handling code here:
        int[] cacVitriduocchon = tblChiTietHDNhap.getSelectedRows();
        // Hàm xóa các vị trí cần xóa
        for (int i = 0; i < cacVitriduocchon.length; i++) {
            String macthdcanxoa = tblChiTietHDNhap.getValueAt(cacVitriduocchon[i], 0).toString();
            ChiTietHDNhapBLL.Xoa(macthdcanxoa);
        }
        ResultSet rs = ChiTietHDNhapBLL.LayTatCaHoaDonNhap();
        ChiTietHDNhapBLL.DoDuLieu(rs, tblChiTietHDNhap);
    }//GEN-LAST:event_XoáCTHDNActionPerformed

    private void XóaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XóaHDActionPerformed
        // TODO add your handling code here:
        int[] cacVitriduocchon = tblHDNhap.getSelectedRows();
        // Hàm xóa các vị trí cần xóa
        for (int i = 0; i < cacVitriduocchon.length; i++) {
            String mahdcanxoa = tblHDNhap.getValueAt(cacVitriduocchon[i], 0).toString();
            HoaDonNhapBLL.Xoa(mahdcanxoa);
        }
        ResultSet rs = HoaDonNhapBLL.LayTatCaHoaDonNhap();
        HoaDonNhapBLL.DanhSachMaHD(rs, tblHDNhap);
    }//GEN-LAST:event_XóaHDActionPerformed

    private void ThêmHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThêmHDActionPerformed
        // TODO add your handling code here:
        FrmThemHDN frm = new FrmThemHDN();
        frm.show();
    }//GEN-LAST:event_ThêmHDActionPerformed

    private void SửaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SửaHDActionPerformed
        // TODO add your handling code here:
        FrmSuaHDN frm = new FrmSuaHDN();
        frm.show();
    }//GEN-LAST:event_SửaHDActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_dtdm", "root", "");
            JasperDesign jasperDesign = JRXmlLoader.load("D:\\PhanMemDuAn01\\DuAn1-PhanMemQLBanHang\\DuAn1-PhanMemQLBanHang\\PhanMemQLBanHang\\src\\Report\\chitiethoadonnhap.jrxml");
            String sql = "select * from ChiTietHDNhap" + ";";
            JRDesignQuery newQuyery = new JRDesignQuery();
            newQuyery.setText(sql);
            jasperDesign.setQuery(newQuyery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, new HashMap(), conn);
            JasperViewer.viewReport(jasperPrint);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNhapHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane NhapHang;
    private javax.swing.JPopupMenu PopupCTHDN;
    private javax.swing.JPopupMenu PopupHDN;
    private javax.swing.JPopupMenu PopupNhapHang;
    private javax.swing.JMenuItem Sửa;
    private javax.swing.JMenuItem SửaCTHDN;
    private javax.swing.JMenuItem SửaHD;
    private javax.swing.JMenuItem ThêmHD;
    private javax.swing.JMenuItem XoáCTHDN;
    private javax.swing.JMenuItem Xóa;
    private javax.swing.JMenuItem XóaHD;
    private javax.swing.JButton bntOK;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JComboBox cbbLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private com.toedter.calendar.JDateChooser jdNgayNhap;
    private javax.swing.JLabel lblMaChiTietHDNhap;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTable tblChiTietHDNhap;
    private javax.swing.JTable tblDanhSachSP;
    private javax.swing.JTable tblHDNhap;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtHanBH;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtIMEI;
    private javax.swing.JTextField txtMaChiTietHDNhap;
    private javax.swing.JTextField txtMaHDNhap;
    private javax.swing.JTextField txtMoTaSP;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiemNCC;
    private javax.swing.JTextField txtTimKiemSP;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
